### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by cjsfj** [thadbryson/flysystem-sync#8]
Would it be possible for you to add a License line to composer.json or a LICENSE file to the repo? Would love to use this library but my company has a strict open sources policy and packages with unknown licenses are not permitted.

Thanks!

**Comment by thadbryson** [comment]
I'm sorry I didn't see this sooner. I added a "license" property to composer.json and made it MIT. It's merged into master and the v1.1.0 tag. 

If you need more than that let me know and I'll see what I can do. 

Also let me know if you use the software and how it goes. 

Thanks, 
Thad
